ebook_metadata:
  title: ༄༅། །བློ་སྦྱོང་དོན་བདུན་མའི་ལྗགས་ཁྲིད་རྒྱལ་སྲས་ཆོས་ཀྱི་མྱུ་གུའི་ཞལ་ལུང༌།།
  authors: []
  sku: LEK-PHI-129
  layers:
  - book_title
  - chapter_title
  - yigchung
web_metadata:
  title:
    en: Words of Gyalse Chokyi Nyugu:Teaching on Seven Points of Mind Training (Transcription
      of teachings (France 1990)
    bo: བློ་སྦྱོང་དོན་བདུན་མའི་ལྗགས་ཁྲིད་རྒྱལ་སྲས་ཆོས་ཀྱི་མྱུ་གུའི་ཞལ་ལུང༌།
  collection:
    en: Lekshey Ling Philosophy Series–  Book 129
    bo: ལེགས་བཤད་གླིང་རིགས་པའི་གཞུང་ལུགས།–  དེབ། ༡༢༩
  author:
    en: Kyabje Dilgo Khyentse Rinpoche
    bo: ༧སྐྱབས་རྗེ་དིལ་མགོ་མཁྱེན་བཙེ་རིན་པོ་ཆེ།
  pusblisher:
    en: Lekshey Ling Publications
    bo: ཀརྨ་ལེགས་བཤད་གླིང།
  sku: LEK-PHI-129
  category:
    en: Mind Training
    bo: བློ་སྦྱོང།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: LEK-PHI-129.epub
  description:
    en: ''
    bo: ''
