id: P000110
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །བློ་སྦྱོང་དོན་བདུན་མའི་ལྗགས་ཁྲིད་རྒྱལ་སྲས་ཆོས་ཀྱི་མྱུ་གུའི་ཞལ་ལུང༌།།
  authors: []
  layers:
  - book_title
  - chapter_title
  - yigchung
  id: LEK-PHI-129
created_at: '2020-01-31T16:08:14.754419'
last_modified_at: '2021-11-25T16:08:14.754419'
quality:
  total_tokens: 26919
  total_non_words: 2314
  non_words_ratio: 0.09
